# This is way out of date; commented out for now
# last updated 1/4/2022
# This must be manually maintained in sync with dependencies specified in pyproject.yml
#
# to create environment:
# > conda env create -f environment.yml
#
# to activate environment (each time):
# > conda activate sarp-connectivity
#
# then install local package:
# > conda develop .
#

# name: sarp-connectivity
# channels:
#   - conda-forge
# dependencies:
#   - python
#   - conda-build
#   - pyarrow=10
#   - python-dotenv>=0.20.0
#   - fastapi>=0.79.0
#   - uvicorn[standard]>=0.18.2
#   - pylint>=2.14.5
#   - black>=22.6.0
#   - requests>=2.28.1
#   - tqdm>=4.64.0
#   - numba=0.56
#   - pyogrio>=0.4.2
#   - geopandas=0.12.1
#   - pandas>=1.4.3
#   - httpx[http2]=>0.23.0
#   - scipy=>1.9.1
#   - shapely=>2.0
#   - openpyxl=>3.0.10

#   # for server deploy; optional
#   - gunicorn=>20.1.0
#   - sentry-sdk=>1.9.0
