[tool.poetry]
name = "sarp-connectivity"
# version is managed in setup.py
version = "0.0.0"
description = "Aquatic Barrier Inventory Visualization & Prioritization Tool"
authors = ["Brendan Ward <bcward@astutespruce.com>"]
license = "MIT"
packages = [{ include = "analysis" }, { include = "api" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
pyarrow = "^13.0.0"
python-dotenv = "^1.0.0"
fastapi = "^0.103.2"
uvicorn = "^0.23.2"
gunicorn = "^21.2.0"
sentry-sdk = "^1.16.0"
rapidfuzz = "^3.1.1"
numpy = "1.25"

[tool.poetry.dev-dependencies]
pylint = "^3.0.1"
black = "^23"
requests = "^2.28.1"
tqdm = "^4.65.0"
numba = "^0.58.0"
pyogrio = "^0.6.0"
geopandas = "^0.14.0"
pandas = "^2.1.1"
httpx = {extras = ["http2"], version = "^0.25.0"}
scipy = "^1.10.1"
shapely = "^2.0.1"
openpyxl = "^3.1.2"
tabulate = "^0.9.0"

[tool.poetry.extras]
deploy = ["gunicorn"]

# wheel is built locally for Arm64
# must be uncommented to install
# pymgl = { path = "../pymgl/dist/pymgl-0.2.2+0.g705372e.dirty-cp310-cp310-macosx_12_0_arm64.whl" }


[tool.isort]
profile = "black"

[tool.ruff]
line-length = 120

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools", "wheel"]
build-backend = "poetry.core.masonry.api"
