[tool.poetry]
name = "sarp-connectivity"
# version is managed in setup.py
version = "0.0.0"
description = "Aquatic Barrier Inventory Visualization & Prioritization Tool"
authors = ["Brendan Ward <bcward@astutespruce.com>"]
license = "MIT"
packages = [{ include = "analysis" }, { include = "api" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
pyarrow = "^14.0.1"
python-dotenv = "^1.0.0"
fastapi = "^0.104.1"
uvicorn = "^0.24.0"
gunicorn = "^21.2.0"
sentry-sdk = "^1.38.0"
rapidfuzz = "^3.1.1"
numpy = "^1.26.2"

[tool.poetry.dev-dependencies]
requests = "^2.31.0"
tqdm = "^4.65.0"
numba = "^0.58.1"
pyogrio = "^0.7.2"
geopandas = "^0.14.1"
pandas = "^2.1.3"
httpx = { extras = ["http2"], version = "^0.25.2" }
scipy = "^1.11.4"
shapely = "^2.0.2"
openpyxl = "^3.1.2"
tabulate = "^0.9.0"
ruff = "^0.1.6"

[tool.poetry.extras]
deploy = ["gunicorn"]

# wheel is built locally for Arm64
# must be uncommented to install
# pymgl = { path = "../pymgl/dist/pymgl-0.4.0-cp310-cp310-macosx_12_0_arm64.whl" }


[tool.ruff]
line-length = 120

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools", "wheel"]
build-backend = "poetry.core.masonry.api"
