[tool.poetry]
name = "sarp-connectivity"
# version is managed in setup.py
version = "0.0.0"
description = "Aquatic Barrier Inventory Visualization & Prioritization Tool"
authors = ["Brendan Ward <bcward@astutespruce.com>"]
license = "MIT"
packages = [{ include = "analysis" }, { include = "api" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
pyarrow = "^16.1.0"
python-dotenv = "^1.0.1"
fastapi = "^0.111.0"
uvicorn = "^0.29.0"
gunicorn = "^22.0.0"
sentry-sdk = "^2.3.1"
rapidfuzz = "^3.9.0"
numpy = "^1.26.4"
python-calamine = "^0.2.0"

[tool.poetry.group.dev.dependencies]
requests = "^2.31.0"
tqdm = "^4.66.4"
numba = "^0.59.1"
pyogrio = "^0.8.0"
geopandas = "^0.14.4"
pandas = "^2.2.2"
httpx = { extras = ["http2"], version = "^0.27.0" }
scipy = "^1.13.1"
shapely = "^2.0.4"
openpyxl = "^3.1.2"
tabulate = "^0.9.0"
ruff = "^0.4.5"
ipykernel = "^6.29.4"

[tool.poetry.extras]
deploy = ["gunicorn"]

# wheel is built locally for Arm64
# must be uncommented to install
# pymgl = { path = "../pymgl/dist/pymgl-0.4.0-cp310-cp310-macosx_12_0_arm64.whl" }


[tool.ruff]
line-length = 120

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools", "wheel"]
build-backend = "poetry.core.masonry.api"
