version: "3.6"
services:
  caddy:
    image: caddy/caddy:2.4.6-alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_certs:/root/.caddy
      - ../../ui/public:/var/www

volumes:
  caddy_certs:
